dimigoin/dimigoin-front-v2

.eslintignore
.eslintrc.js
.gitignore
.storybook/config.js
.storybook/main.js
config-overrides.js
package.json
src/api/deliverier.ts
src/api/index.ts
src/components/Footer.tsx
src/components/dimiru/DimiCard.stories.js
src/components/dimiru/DimiCard.tsx
src/components/dimiru/DimiFooter.stories.js
src/components/dimiru/DimiFooter.tsx
src/components/dimiru/DimiIcon.stories.js
src/components/dimiru/DimiIcon.tsx
src/pages/Draft.tsx
src/pages/ExplorerFound.tsx
src/pages/Main.tsx
src/pages/Meal.tsx
src/pages/NotFound.tsx
src/pages/index.ts
src/react-app-env.d.ts
src/router/index.tsx
src/serviceWorker.ts

refactor(style): apply Eslint fixes

---

src/pages/Login.tsx
src/pages/index.ts
src/router/Auth.tsx
src/router/index.tsx

feat(src/pages/Login.tsx) : add Login page and route

---

src/components/dimiru/DimiButton.stories.js
src/components/dimiru/DimiButton.tsx

this solves #40 
1. 중복되는 변수명은 변경했습니다
2. Click prop 함수의 파라메터에 Event 받을 수 있도록 했습니다.
3. a태그에 onClick을 Lint에 맞게 수정했습니다

fix : type for DimiButton / code spelling

---

.storybook/webpack.config.js
package.json

* chore(storybook): fix webpack setting for emotion
* chore: remove babel-loader from devDependencies
Co-authored-by: JunhoYeo <32605822+JunhoYeo@users.noreply.github.com>

chore: load some components

---

package.json
src/components/ContentWrapper.tsx
src/components/dimiru/DimiBadgeGroup.tsx
src/pages/management/Circle.tsx
src/pages/management/index.tsx
src/router/Management.tsx
src/router/index.tsx

feat : Dimiru/DimiBadgeGroup 그리고 ContentWrapper 그리고 manangement/circle

---

src/components/dimiru/DimiLoading.stories.js
src/components/dimiru/DimiLoading.tsx

feat(dimiru/DimiLoading): create DimiLoading component

---

.github/workflows/main.yml

fix : disable action on pull request

fix : disable action on pull request

---

src/components/dimiru/DimiButtonGroup.tsx

feat(components/dimiru) : add DimiButtonGroup

---

src/api/axios.js
src/api/magician.js
src/api/service-base.js
src/errors/api-error.js

feat : HTTP API Library support

---

src/api/circle/circle.service.js
src/api/circle/circle.struct.js
src/api/circle/index.js
src/api/util/handle-circle-status.js

feat(API) : Circle API Support

---

src/components/PrivateRoute.tsx
src/router/Auth.tsx
src/router/Management.tsx
src/router/Request.tsx
src/router/index.tsx

feat: PrivateRoute for before login

---

src/components/dimiru/DimiButtonGroup.tsx
src/pages/management/Circle.tsx

feat : add CircleApplicationManage

---

src/components/GlobalStyle.ts
src/pages/request/CircleApplication.tsx

* Merge develop into master  (#34)
* chore: install emotion(CSS-in-JS) (#9)
* refactor: styled-components to emotion
* chore(storybook): setup storybook (#21)
* chore: install storybook
* chore: intergrate dimiru with storybook
* refactor: change page import style (#23)
* chore(lint): configure eslint with husky, lint staged (#22)
Co-authored-by: JUNO <hanaro0704@naver.com>
* chore(style): re-setting emotion(CSS-in-JS) (#24)
* feat(pages): implement Main page (#26)
* feat(pages/main): layout for Main
* feat(pages/main): align columns and show logo, default photo
* feat: IE redirect to static html file (#27)
* [ImgBot] Optimize images (#28)
/public/static/font/dimigoincon.svg -- 31.27kb -> 30.62kb (2.09%)
Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>
Co-authored-by: ImgBotApp …

fix: sure question before apply circle application (#99)

---

src/api/axios.js
src/api/circle/circle.service.js
src/api/circle/circle.struct.js
src/api/util/handle-circle-status.js
src/pages/management/CircleApplication.tsx

fix : Circle API Fixed

---

package.json
src/pages/request/CircleInformation.tsx
src/utils/autolinker.ts

feat: apply autolinker

---

public/index.html
src/components/PrivateRoute.tsx
src/router/index.tsx

feat: add title

---

README.md

chore: Add project README

---

src/pages/request/CircleApplication.tsx
src/pages/request/CircleInformation.tsx

fix: fix load circle info bug

---

src/api/index.ts
src/utils/auth.ts

fix : change localstorage's accessToken key to accessToken2

---

src/components/dimiru/DimiInput.tsx
src/pages/Login.tsx

feat: login when press enter key

---

src/components/CircleCard.tsx
src/components/dimiru/DimiCard.tsx
src/components/dimiru/DimiInput.tsx
src/pages/Login.tsx
src/pages/Main.tsx
src/pages/management/CircleApplication.tsx
src/pages/management/CircleCreation.tsx
src/pages/request/CircleApplication.tsx
src/pages/request/CircleInformation.tsx
src/utils/swal.ts

refactor: circle feature

---

src/pages/management/CircleApplication.tsx

fix : sort application form question by question id key

---

src/pages/Main.tsx

> 선생님으로 로그인했을 때 학번 정보를 숨기고 ` 선생님`을 붙입니다.

fix: hide serial for teacher

---

src/pages/NotFound.tsx

feat: create 404 NotFound page

---

src/pages/NotFound.tsx

Deploy to production 🚀

---

src/components/dimiru/DimiButtonGroup.tsx
src/pages/management/CircleApplication/gql.ts
src/pages/management/CircleApplication/index.tsx
src/pages/management/CircleApplication/styles.ts
src/pages/management/CircleApplication/types.ts

feat: graphql application view with applied circle chips

---

src/components/CircleCard.tsx
src/pages/request/CircleInformation.tsx

지원사들에게 면접 시간이 표시되게 했습니다
떨어지면 안떠요(..)

feat : add interview time view for appliers

---

src/pages/Main.tsx

feat: change notice

---

package.json
src/components/CircleCard.tsx
src/pages/request/CircleInformation.tsx

this fixes my sentimental vibe

feat : add cherry blossom 🎉🎉🌺🌸🌸

---

package.json
src/components/CircleCard.tsx
src/pages/Main.tsx
src/pages/request/CircleInformation.tsx

Merge dev to master

---

src/components/CircleCard.tsx
src/components/dimiru/DimiBadgeGroup.tsx
src/components/dimiru/DimiButton.tsx
src/components/dimiru/DimiButtonGroup.tsx
src/pages/Login.tsx
src/pages/management/CircleApplication/index.tsx
src/pages/management/CircleCreation.tsx
src/pages/request/CircleApplication.tsx
src/pages/request/CircleInformation.tsx

refactor: rename click prop to onClick for button components

---

package.json
src/pages/Login.tsx

fix: login bugs
